### ISSUE TITLE
IE & Chrome automatically selects first value on dependent list when using OptGroups

### ISSUE THREAD

**Issue by tof06** [kartik-v/dependent-dropdown#39] opened 2016-02-01 13:12 UTC
Hello, 

I noticed a strange behavior with Chrome & IE 11 (also on your demo page).

When you select a value on parent list, the dependant dropdown will load results. If the server respond a list with groups, and with a `selected:""`, Firefox will correctly show the  placeholder, but Chrome & IE will select the first value.

It seems that this line is causing the problem (or, at least, removing it solves it :))
https://github.com/kartik-v/dependent-dropdown/blob/master/js/dependent-dropdown.js#L152

Is there any reason to disable the pseudo placeholder option when using optGroups ?

Thanks.

**Comment by kartik-v** [comment] 2016-02-02 04:30
Yes this was included. Because with opt-groups you normally do not have an empty option value. The empty option value has to be assigned to some opt-group - else there will be a validation error in validating and rendering the groups properly...

**Comment by kartik-v** [comment] 2016-02-02 04:47
Yes this was included because with opt-groups you normally do not have an empty option value. The empty option value has to be assigned to some opt-group - else there will be a validation error in validating and rendering the groups and options properly... 

You need to send a default `selected` property in your json via ajax ...  to ensure that the values are selected correctly for opt-groups.

**Comment by kartik-v** [comment] 2016-02-02 05:05
BTW... note that there is no pseudo placeholder property for HTML SELECT inputs.

You need to display an empty option (or similar) with a different CSS to make it look like a placeholder.

**Comment by tof06** [comment] 2016-02-02 07:44
Not sure I understand :)

My ajax response already send a `selected:""` property. But because the `option value=""` is set to `disabled` when optgroups are used, it seems that IE and Chrome can't select it to display the placeholder. 

> You need to display an empty option (or similar) with a different CSS to make it look like a placeholder.

I'm using the SELECT2 depdrop type, so, I think everything is ok with placeholders. Btw, when I remove that line, everything is OK on the three major browsers.

**Comment by kartik-v** [comment] 2017-07-25 11:42
Not able to reproduce the issue - check with the latest code base and confirm if any issues and will reopen this.

**Closed by kartik-v** 2017-07-25 11:42 UTC
